name: Quality Assurance

on:
  push:
    branches:
      - main
      - issue*
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Run coverage report
        working-directory: loan
        run: ./gradlew test jacocoReport -i
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: loan/build/reports/jacoco

  sonarqube:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Download Test Report Artifact
        uses: actions/download-artifact@v3
        with:
          name: report
          path: loan/build/reports/jacoco
      - run: ./gradlew sonar
        working-directory: loan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
